# This is a basic workflow that is manually triggered

name: Deploy and Release
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  deploy:
    name: Build and deploy app
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env: 
      working-directory: ./app

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
        
      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16
          
      - name: Install packages
        run: yarn
        working-directory: ${{ env.working-directory }}
          
      - name: Compile source
        run: yarn run build
        working-directory: ${{ env.working-directory }}
        env:
          REACT_APP_PUBNUB_PUBLISH_KEY: ${{ secrets.PUBNUB_PUBLISH_KEY }}
          REACT_APP_PUBNUB_SUBSCRIBE_KEY: ${{ secrets.PUBNUB_SUBSCRIBE_KEY }}
        
      - name: Upload to host via SFTP
        uses: zurb/sftp-upload-action@1.3
        with:
          host: ${{ secrets.WEBGO_SFTP_HOST }}
          port: ${{ secrets.WEBGO_SFTP_PORT }}
          username: ${{ secrets.WEBGO_SFTP_USERNAME }}
          password: ${{ secrets.WEBGO_SFTP_PASSWORD }}
          localDir: ./app/build
          remoteDir: /home/www/de.absolutholz.uno
    
      # Runs a single command using the runners shell
      # - name: Send greeting
      #   run: echo "Hello ${{ github.event.inputs.name }}"
